<a href="https://colab.research.google.com/github/barkle2/Programming/blob/master/%5BPython%5D%20Tutorial/kosis_API_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 통계청 OPEN API 활용 예제

### 1. 인증키 받기
- 가장 먼저 해야하는 일은 KOSIS 공유서비스(https://kosis.kr/openapi/index/index.jsp) 사이트에 가입하고, 인증키를 받는 것입니다.
- 인증키 유효기간은 2년입니다.

In [1]:
key = "MDUwYjkzYmRhZjc4Yzk5M2QyZDg1NDBhNjNlOTNjZmQ="

### 2. 통계목록 확인
- 요청 URL: http://kosis.kr/openapi/statisticsList.do?method=getList
- 요청 변수(String)
  - apiKey : 인증키
  - vwCd
    - MT_ZTITLE : 국내통계 주제별
    - MT_OTITLE : 국내통계 기관별
  - parentListId
    - MT_ZTITLE : 노동(D)
    - MT_OTITLE : 통계청(101), 고용노동부(118)
  - format: json

- API 호출을 위한 Query 문 생성

In [2]:
query = "https://kosis.kr/openapi/statisticsList.do?method=getList&apiKey={}&vwCd={}&parentListId={}&format=json&jsonVD=Y"
vwCd = "MT_ZTITLE"
parentListId = "D"

query = query.format(key, vwCd, parentListId)

- requests library를 활용하여 API 호출

In [3]:
import requests
import pandas as pd
from google.colab import files
import time, random

- '국내통계 주제별' 중 '노동'에 해당하는 통계목록은 다음과 같다.

In [4]:
r = requests.get(query)
r.content
data = r.json()
df = pd.DataFrame(data)
df

             LIST_NM      VW_CD     VW_NM LIST_ID
0   경력단절여성등의경제활동실태조사  MT_ZTITLE  국내통계 주제별     D_1
1           경제활동인구조사  MT_ZTITLE  국내통계 주제별     D_2
2            고령자고용현황  MT_ZTITLE  국내통계 주제별     D_3
3             고용보험통계  MT_ZTITLE  국내통계 주제별     D_4
4          고용허가제고용동향  MT_ZTITLE  국내통계 주제별     D_5
5        고용형태별근로실태조사  MT_ZTITLE  국내통계 주제별     D_6
6           구직급여신청동향  MT_ZTITLE  국내통계 주제별     D_7
7             근로환경조사  MT_ZTITLE  국내통계 주제별     D_8
8         기업직업훈련실태조사  MT_ZTITLE  국내통계 주제별     D_9
9       기업체장애인고용실태조사  MT_ZTITLE  국내통계 주제별    D_10
10           노동생산성지수  MT_ZTITLE  국내통계 주제별    D_11
11            노사분규통계  MT_ZTITLE  국내통계 주제별    D_12
12       대졸자직업이동경로조사  MT_ZTITLE  국내통계 주제별    D_13
13          박사인력활동조사  MT_ZTITLE  국내통계 주제별    D_14
14     사업체기간제근로자현황조사  MT_ZTITLE  국내통계 주제별    D_15
15          사업체노동력조사  MT_ZTITLE  국내통계 주제별    D_16
16         사업체노동실태현황  MT_ZTITLE  국내통계 주제별    D_17
17      산업기술인력수급실태조사  MT_ZTITLE  국내통계 주제별    D_18
18            산재보험통계  MT_ZTITLE  국내통계 주제별    D_19
19          산재보험패널조사  MT_ZTITLE  국내통계 주제별    D_20
20         여성관리자패널조사  MT_ZTITLE  국내통계 주제별    D_21
21      워크넷구인구직및취업동향  MT_ZTITLE  국내통계 주제별    D_22
22      이민자체류실태및고용조사  MT_ZTITLE  국내통계 주제별    D_23
23           일자리이동통계  MT_ZTITLE  국내통계 주제별   D_001
24           일자리행정통계  MT_ZTITLE  국내통계 주제별    D_24
25     임금근로일자리동향행정통계  MT_ZTITLE  국내통계 주제별    D_25
26            육아휴직통계  MT_ZTITLE  국내통계 주제별   B_001
27          작업환경실태조사  MT_ZTITLE  국내통계 주제별    D_26
28       장애인경제활동실태조사  MT_ZTITLE  국내통계 주제별    D_27
29         장애인고용패널조사  MT_ZTITLE  국내통계 주제별    D_28
30      장애인구인구직및취업동향  MT_ZTITLE  국내통계 주제별    D_29
31         장애인의무고용현황  MT_ZTITLE  국내통계 주제별    D_30
32        전국노동조합조직현황  MT_ZTITLE  국내통계 주제별    D_31
33           지역별고용조사  MT_ZTITLE  국내통계 주제별    D_32
34       직종별사업체노동력조사  MT_ZTITLE  국내통계 주제별    D_33
35            청년패널조사  MT_ZTITLE  국내통계 주제별    D_34
36          한국노동패널조사  MT_ZTITLE  국내통계 주제별    D_35

- 경제활동인구조사 통계 내에도 여러 개의 세부 통계목록이 존재한다.

In [5]:
query = "https://kosis.kr/openapi/statisticsList.do?method=getList&apiKey={}&vwCd={}&parentListId={}&format=json&jsonVD=Y"
vwCd = "MT_ZTITLE"
parentListId = "D_2"

query = query.format(key, vwCd, parentListId)

In [6]:
r = requests.get(query)
r.content
data = r.json()
df = pd.DataFrame(data)
df

                                             LIST_NM  ...  LIST_ID
0             경제활동인구총괄(공식 실업률, 구직기간 4주기준, 1999.6~현재)  ...      B11
1                             계절조정 경제활동인구(1999.6~현재)  ...      B12
2                                       취업자(1963~현재)  ...      B17
3    실업자(구직기간 4주 기준, 1999.5월 이전자료는 경제활동인구총괄 1주기준 참조)  ...      B16
4   실업률(구직기간 4주 기준, 1999. 5월 이전자료는 경제활동인구총괄 1주기준 참조)  ...      B15
5           비경제활동인구(1999. 5월 이전자료는 경제활동인구총괄 1주기준 참조)  ...      B14
6                  경제활동인구총괄(구직기간 1주기준, 1963~2014.12)  ...      B13
7                                         근로형태별 부가조사  ...  101_B1A
8                                           청년층 부가조사  ...   B1A_18
9                                           고령층 부가조사  ...   B1A_20
10                                        비임금근로 부가조사  ...   B1A_22
11                                비임금근로 부가조사(농림어업제외)  ...   B1A_24
12                                      비경제활동인구 부가조사  ...   B1A_26
13                         시계열 보정(2018.2.14 공표) 前 자료  ...  B1A_101

[14 rows x 4 columns]

- 가장 많이 사용되는 '경제활동인구총괄(공식 실업률, 구직기간 4주기준, 1999.6~현재)' 표의 세부 목록을 확인한다.

In [7]:
query = "https://kosis.kr/openapi/statisticsList.do?method=getList&apiKey={}&vwCd={}&parentListId={}&format=json&jsonVD=Y"
vwCd = "MT_ZTITLE"
parentListId = "B11"

query = query.format(key, vwCd, parentListId)

In [8]:
r = requests.get(query)
r.content
data = r.json()
df = pd.DataFrame(data)
df

                   TBL_NM        TBL_ID      VW_CD     VW_NM ORG_ID
0            성별 경제활동인구 총괄   DT_1DA7001S  MT_ZTITLE  국내통계 주제별    101
1           연령별 경제활동인구 총괄   DT_1DA7002S  MT_ZTITLE  국내통계 주제별    101
2            교육정도별 경제활동인구   DT_1DA7003S  MT_ZTITLE  국내통계 주제별    101
3        행정구역(시도)별 경제활동인구   DT_1DA7004S  MT_ZTITLE  국내통계 주제별    101
4            성/연령별 경제활동인구   DT_1DA7012S  MT_ZTITLE  국내통계 주제별    101
5          성/교육정도별 경제활동인구   DT_1DA7013S  MT_ZTITLE  국내통계 주제별    101
6      행정구역(시도)/성별 경제활동인구   DT_1DA7014S  MT_ZTITLE  국내통계 주제별    101
7     행정구역(시도)/연령별 경제활동인구   DT_1DA7015S  MT_ZTITLE  국내통계 주제별    101
8   행정구역(시도)/교육정도별 경제활동인구   DT_1DA7016S  MT_ZTITLE  국내통계 주제별    101
9              고용보조지표(전체)   DT_1DA7300S  MT_ZTITLE  국내통계 주제별    101
10    고용보조지표(청년층, 15~29세)  DT_1DA7300AS  MT_ZTITLE  국내통계 주제별    101

- '연령별 경제활동인구 총괄' 표의 통계자료를 조회하기 위해 필요한 테이블 ID(TBL_ID:DT_1DA7002S)와 기관 ID(ORG_ID:101)를 얻었다.

In [9]:
tbl_id = 'DT_1DA7012S'
org_id = '101'

## 3. 통계자료 조회

### 3-1. 최신 시점 찾기
- 현재 기준으로 가장 최신 통계가 언제의 통계인지 확인한다.
- '횡단면 조회' 자료를 받아 최신 통계 시점을 확인한다.
- 통계청 OPEN API 사이트에서 횡단면 조회 query 예제 복사

In [15]:
# 0:apiKey, 1:itmId, 2:objL1, 3:objL2, 4:prdSe, 5:loadGubun, 6:ordId, 7:tblId
query = "https://kosis.kr/openapi/Param/statisticsParameterData.do?method=getList&apiKey={0}&itmId={1}+&objL1={2}+&objL2={3}&objL3=&objL4=&objL5=&objL6=&objL7=&objL8=&format=json&jsonVD=Y&prdSe={4}&newEstPrdCnt=1&loadGubun={5}&orgId={6}&tblId={7}"

- 통계청 OPEN API 사이트에서 항목, 분류 value 찾기

In [16]:
# 항목
itm_id = {
    "인구":"T10",
    "경제활동인구":"T20",
    "취업자":"T30",
    "실업자":"T40",
    "비경제활동인구":"T50",
    "경제활동참가율":"T60",
    "실업률":"T80",
    "고용률":"T90"
}

# 성별 분류
sex_id = {
  "계": "0",
  "남자": "2",
  "여자": "3"
}

# 연령 분류
age_id = {
     "15세 이상 전체": "00",
     "15 - 19세": "10",
     "20 - 29세": "20",
     "20 - 24세": "201",
     "25 - 29세": "202",
     "30 - 39세": "30",
     "30 - 34세": "301",
     "35 - 39세": "302",
     "40 - 49세": "40",
     "40 - 44세": "401",
     "45 - 49세": "402",
     "50 - 59세": "50",
     "50 - 54세": "501",
     "55 - 59세": "502",
     "60세 이상": "60",
     "60 - 64세": "601",
     "65세 이상": "602",
     "15 - 64세": "63",
     "15 - 24세": "70",
     "15 - 29세": "75"
}

- 그 밖에 필요한 변수는 직접 입력

In [17]:
prd_se = 'M'
load_gubun = '2'

query = query.format(key, itm_id['인구'], sex_id['계'], age_id['15세 이상 전체'], prd_se, load_gubun, org_id, tbl_id)
query

'https://kosis.kr/openapi/Param/statisticsParameterData.do?method=getList&apiKey=MDUwYjkzYmRhZjc4Yzk5M2QyZDg1NDBhNjNlOTNjZmQ=&itmId=T10+&objL1=0+&objL2=00&objL3=&objL4=&objL5=&objL6=&objL7=&objL8=&format=json&jsonVD=Y&prdSe=M&newEstPrdCnt=1&loadGubun=2&orgId=101&tblId=DT_1DA7012S'

- '횡단면 조회'의 PRD_DE 값이 가장 최근 시점(end_prd_de)이 된다.

In [18]:
r = requests.get(query)
r.content
data = r.json()
df = pd.DataFrame(data)
df

         TBL_NM  PRD_DE       TBL_ID   ITM_NM  ... C1_NM C2_NM C1_NM_ENG C2_NM_ENG
0  성/연령별 경제활동인구  202011  DT_1DA7012S  15세이상인구  ...     계     계     Total     Total

[1 rows x 21 columns]

In [19]:
end_prd_de = df['PRD_DE'][0]
end_prd_de

'202011'

- 가장 최근 시점을 구했으니 시계열 조회를 한다.
- 통계청 OPEN API 사이트에서 시계열 조회 query 예제 복사

In [20]:
# 0:apiKey, 1:itmId, 2:objL1, 3:objL2, 4:prdSe, 5:startPrdDe, 6:endPrdDe, 7:loadGubun, 8:orgId, 9:tblId
query = "https://kosis.kr/openapi/Param/statisticsParameterData.do?method=getList&apiKey={0}&itmId={1}+&objL1={2}+&objL2={3}&objL3=&objL4=&objL5=&objL6=&objL7=&objL8=&format=json&jsonVD=Y&prdSe={4}&startPrdDe={5}&endPrdDe={6}&loadGubun={7}&orgId={8}&tblId={9}"

start_prd_de = '199906'
load_gubun = '1'
org_id
tbl_id

query.format(key, itm_id['인구'], sex_id['계'], age_id['15세 이상 전체'], prd_se, start_prd_de, end_prd_de, load_gubun, org_id, tbl_id )

'https://kosis.kr/openapi/Param/statisticsParameterData.do?method=getList&apiKey=MDUwYjkzYmRhZjc4Yzk5M2QyZDg1NDBhNjNlOTNjZmQ=&itmId=T10+&objL1=0+&objL2=00&objL3=&objL4=&objL5=&objL6=&objL7=&objL8=&format=json&jsonVD=Y&prdSe=M&startPrdDe=199906&endPrdDe=202011&loadGubun=1&orgId=101&tblId=DT_1DA7012S'

In [21]:
# 자료 저장을 위한 DataFrame
df = pd.DataFrame()

- itm_id(항목)과 obj_lev2(연령구분)을 반복문으로 바꿔가며 조회하고, df에 모두 합친다.

In [22]:
for item in itm_id.values():
  for sex in sex_id.values():
    for obj in age_id.values():    
      query_temp = query.format(key, item, sex, obj, prd_se, start_prd_de, end_prd_de, load_gubun, org_id, tbl_id )        
      r = requests.get(query_temp)

      data = r.json()
      df_temp = pd.DataFrame(data)
      df = df.append(df_temp, ignore_index=True)
      print(item, sex, obj, df.shape)
      time.sleep(random.uniform(2,8))

T10 0 00 (258, 21)
T10 0 10 (516, 21)
T10 0 20 (774, 21)
T10 0 201 (1032, 21)
T10 0 202 (1290, 21)
T10 0 30 (1548, 21)
T10 0 301 (1806, 21)
T10 0 302 (2064, 21)
T10 0 40 (2322, 21)
T10 0 401 (2580, 21)
T10 0 402 (2838, 21)
T10 0 50 (3096, 21)
T10 0 501 (3354, 21)
T10 0 502 (3612, 21)
T10 0 60 (3870, 21)
T10 0 601 (4128, 21)
T10 0 602 (4386, 21)
T10 0 63 (4644, 21)
T10 0 70 (4902, 21)
T10 0 75 (5160, 21)
T10 2 00 (5418, 21)
T10 2 10 (5676, 21)
T10 2 20 (5934, 21)
T10 2 201 (6192, 21)
T10 2 202 (6450, 21)
T10 2 30 (6708, 21)
T10 2 301 (6966, 21)
T10 2 302 (7224, 21)
T10 2 40 (7482, 21)
T10 2 401 (7740, 21)
T10 2 402 (7998, 21)
T10 2 50 (8256, 21)
T10 2 501 (8514, 21)
T10 2 502 (8772, 21)
T10 2 60 (9030, 21)
T10 2 601 (9288, 21)
T10 2 602 (9546, 21)
T10 2 63 (9804, 21)
T10 2 70 (10062, 21)
T10 2 75 (10320, 21)
T10 3 00 (10578, 21)
T10 3 10 (10836, 21)
T10 3 20 (11094, 21)
T10 3 201 (11352, 21)
T10 3 202 (11610, 21)
T10 3 30 (11868, 21)
T10 3 301 (12126, 21)
T10 3 302 (12384, 21)
T10 3 40 (12642, 21)
T10 3 401 (12900, 21)
T10 3 402 (13158, 21)
T10 3 50 (13416, 21)
T10 3 501 (13674, 21)
T10 3 502 (13932, 21)
T10 3 60 (14190, 21)
T10 3 601 (14448, 21)
T10 3 602 (14706, 21)
T10 3 63 (14964, 21)
T10 3 70 (15222, 21)
T10 3 75 (15480, 21)
T20 0 00 (15738, 21)
T20 0 10 (15996, 21)
T20 0 20 (16254, 21)
T20 0 201 (16512, 21)
T20 0 202 (16770, 21)
T20 0 30 (17028, 21)
T20 0 301 (17286, 21)
T20 0 302 (17544, 21)
T20 0 40 (17802, 21)
T20 0 401 (18060, 21)
T20 0 402 (18318, 21)
T20 0 50 (18576, 21)
T20 0 501 (18834, 21)
T20 0 502 (19092, 21)
T20 0 60 (19350, 21)
T20 0 601 (19608, 21)
T20 0 602 (19866, 21)
T20 0 63 (20124, 21)
T20 0 70 (20382, 21)
T20 0 75 (20640, 21)
T20 2 00 (20898, 21)
T20 2 10 (21156, 21)
T20 2 20 (21414, 21)
T20 2 201 (21672, 21)
T20 2 202 (21930, 21)
T20 2 30 (22188, 21)
T20 2 301 (22446, 21)
T20 2 302 (22704, 21)
T20 2 40 (22962, 21)
T20 2 401 (23220, 21)
T20 2 402 (23478, 21)
T20 2 50 (23736, 21)
T20 2 501 (23994, 21)
T20 2 502 (24252, 21)
T20 2 60 (24510, 21)
T20 2 601 (24768, 21)
T20 2 602 (25026, 21)
T20 2 63 (25284, 21)
T20 2 70 (25542, 21)
T20 2 75 (25800, 21)
T20 3 00 (26058, 21)
T20 3 10 (26316, 21)
T20 3 20 (26574, 21)
T20 3 201 (26832, 21)
T20 3 202 (27090, 21)
T20 3 30 (27348, 21)
T20 3 301 (27606, 21)
T20 3 302 (27864, 21)
T20 3 40 (28122, 21)
T20 3 401 (28380, 21)
T20 3 402 (28638, 21)
T20 3 50 (28896, 21)
T20 3 501 (29154, 21)
T20 3 502 (29412, 21)
T20 3 60 (29670, 21)
T20 3 601 (29928, 21)
T20 3 602 (30186, 21)
T20 3 63 (30444, 21)
T20 3 70 (30702, 21)
T20 3 75 (30960, 21)
T30 0 00 (31218, 21)
T30 0 10 (31476, 21)
T30 0 20 (31734, 21)
T30 0 201 (31992, 21)
T30 0 202 (32250, 21)
T30 0 30 (32508, 21)
T30 0 301 (32766, 21)
T30 0 302 (33024, 21)
T30 0 40 (33282, 21)
T30 0 401 (33540, 21)
T30 0 402 (33798, 21)
T30 0 50 (34056, 21)
T30 0 501 (34314, 21)
T30 0 502 (34572, 21)
T30 0 60 (34830, 21)
T30 0 601 (35088, 21)
T30 0 602 (35346, 21)
T30 0 63 (35604, 21)
T30 0 70 (35862, 21)
T30 0 75 (36120, 21)
T30 2 00 (36378, 21)
T30 2 10 (36636, 21)
T30 2 20 (36894, 21)
T30 2 201 (37152, 21)
T30 2 202 (37410, 21)
T30 2 30 (37668, 21)
T30 2 301 (37926, 21)
T30 2 302 (38184, 21)
T30 2 40 (38442, 21)
T30 2 401 (38700, 21)
T30 2 402 (38958, 21)
T30 2 50 (39216, 21)
T30 2 501 (39474, 21)
T30 2 502 (39732, 21)
T30 2 60 (39990, 21)
T30 2 601 (40248, 21)
T30 2 602 (40506, 21)
T30 2 63 (40764, 21)
T30 2 70 (41022, 21)
T30 2 75 (41280, 21)
T30 3 00 (41538, 21)
T30 3 10 (41796, 21)
T30 3 20 (42054, 21)
T30 3 201 (42312, 21)
T30 3 202 (42570, 21)
T30 3 30 (42828, 21)
T30 3 301 (43086, 21)
T30 3 302 (43344, 21)
T30 3 40 (43602, 21)
T30 3 401 (43860, 21)
T30 3 402 (44118, 21)
T30 3 50 (44376, 21)
T30 3 501 (44634, 21)
T30 3 502 (44892, 21)
T30 3 60 (45150, 21)
T30 3 601 (45408, 21)
T30 3 602 (45666, 21)
T30 3 63 (45924, 21)
T30 3 70 (46182, 21)
T30 3 75 (46440, 21)
T40 0 00 (46698, 21)
T40 0 10 (46956, 21)
T40 0 20 (47214, 21)
T40 0 201 (47472, 21)
T40 0 202 (47730, 21)
T40 0 30 (47988, 21)
T40 0 301 (48246, 21)
T40 0 302 (48504, 21)
T40 0 40 (48762, 21)
T40 0 401 (49020, 21)
T40 0 402 (49278, 21)
T40 0 50 (49536, 21)
T40 0 501 (49794, 21)
T40 0 502 (50052, 21)
T40 0 60 (50310, 21)
T40 0 601 (50568, 21)
T40 0 602 (50826, 21)
T40 0 63 (51084, 21)
T40 0 70 (51342, 21)
T40 0 75 (51600, 21)
T40 2 00 (51858, 21)
T40 2 10 (52116, 21)
T40 2 20 (52374, 21)
T40 2 201 (52632, 21)
T40 2 202 (52890, 21)
T40 2 30 (53148, 21)
T40 2 301 (53406, 21)
T40 2 302 (53664, 21)
T40 2 40 (53922, 21)
T40 2 401 (54180, 21)
T40 2 402 (54438, 21)
T40 2 50 (54696, 21)
T40 2 501 (54954, 21)
T40 2 502 (55212, 21)
T40 2 60 (55470, 21)
T40 2 601 (55728, 21)
T40 2 602 (55986, 21)
T40 2 63 (56244, 21)
T40 2 70 (56502, 21)
T40 2 75 (56760, 21)
T40 3 00 (57018, 21)
T40 3 10 (57276, 21)
T40 3 20 (57534, 21)
T40 3 201 (57792, 21)
T40 3 202 (58050, 21)
T40 3 30 (58308, 21)
T40 3 301 (58566, 21)
T40 3 302 (58824, 21)
T40 3 40 (59082, 21)
T40 3 401 (59340, 21)
T40 3 402 (59598, 21)
T40 3 50 (59856, 21)
T40 3 501 (60114, 21)
T40 3 502 (60372, 21)
T40 3 60 (60630, 21)
T40 3 601 (60888, 21)
T40 3 602 (61146, 21)
T40 3 63 (61404, 21)
T40 3 70 (61662, 21)
T40 3 75 (61920, 21)
T50 0 00 (62178, 21)
T50 0 10 (62436, 21)
T50 0 20 (62694, 21)
T50 0 201 (62952, 21)
T50 0 202 (63210, 21)
T50 0 30 (63468, 21)
T50 0 301 (63726, 21)
T50 0 302 (63984, 21)
T50 0 40 (64242, 21)
T50 0 401 (64500, 21)
T50 0 402 (64758, 21)
T50 0 50 (65016, 21)
T50 0 501 (65274, 21)
T50 0 502 (65532, 21)
T50 0 60 (65790, 21)
T50 0 601 (66048, 21)
T50 0 602 (66306, 21)
T50 0 63 (66564, 21)
T50 0 70 (66822, 21)
T50 0 75 (67080, 21)
T50 2 00 (67338, 21)
T50 2 10 (67596, 21)
T50 2 20 (67854, 21)
T50 2 201 (68112, 21)
T50 2 202 (68370, 21)
T50 2 30 (68628, 21)
T50 2 301 (68886, 21)
T50 2 302 (69144, 21)
T50 2 40 (69402, 21)
T50 2 401 (69660, 21)
T50 2 402 (69918, 21)
T50 2 50 (70176, 21)
T50 2 501 (70434, 21)
T50 2 502 (70692, 21)
T50 2 60 (70950, 21)
T50 2 601 (71208, 21)
T50 2 602 (71466, 21)
T50 2 63 (71724, 21)
T50 2 70 (71982, 21)
T50 2 75 (72240, 21)
T50 3 00 (72498, 21)
T50 3 10 (72756, 21)
T50 3 20 (73014, 21)
T50 3 201 (73272, 21)
T50 3 202 (73530, 21)
T50 3 30 (73788, 21)
T50 3 301 (74046, 21)
T50 3 302 (74304, 21)
T50 3 40 (74562, 21)
T50 3 401 (74820, 21)
T50 3 402 (75078, 21)
T50 3 50 (75336, 21)
T50 3 501 (75594, 21)
T50 3 502 (75852, 21)
T50 3 60 (76110, 21)
T50 3 601 (76368, 21)
T50 3 602 (76626, 21)
T50 3 63 (76884, 21)
T50 3 70 (77142, 21)
T50 3 75 (77400, 21)
T60 0 00 (77658, 21)
T60 0 10 (77916, 21)
T60 0 20 (78174, 21)
T60 0 201 (78432, 21)
T60 0 202 (78690, 21)
T60 0 30 (78948, 21)
T60 0 301 (79206, 21)
T60 0 302 (79464, 21)
T60 0 40 (79722, 21)
T60 0 401 (79980, 21)
T60 0 402 (80238, 21)
T60 0 50 (80496, 21)
T60 0 501 (80754, 21)
T60 0 502 (81012, 21)
T60 0 60 (81270, 21)
T60 0 601 (81528, 21)
T60 0 602 (81786, 21)
T60 0 63 (82044, 21)
T60 0 70 (82302, 21)
T60 0 75 (82560, 21)
T60 2 00 (82818, 21)
T60 2 10 (83076, 21)
T60 2 20 (83334, 21)
T60 2 201 (83592, 21)
T60 2 202 (83850, 21)
T60 2 30 (84108, 21)
T60 2 301 (84366, 21)
T60 2 302 (84624, 21)
T60 2 40 (84882, 21)
T60 2 401 (85140, 21)
T60 2 402 (85398, 21)
T60 2 50 (85656, 21)
T60 2 501 (85914, 21)
T60 2 502 (86172, 21)
T60 2 60 (86430, 21)
T60 2 601 (86688, 21)
T60 2 602 (86946, 21)
T60 2 63 (87204, 21)
T60 2 70 (87462, 21)
T60 2 75 (87720, 21)
T60 3 00 (87978, 21)
T60 3 10 (88236, 21)
T60 3 20 (88494, 21)
T60 3 201 (88752, 21)
T60 3 202 (89010, 21)
T60 3 30 (89268, 21)
T60 3 301 (89526, 21)
T60 3 302 (89784, 21)
T60 3 40 (90042, 21)
T60 3 401 (90300, 21)
T60 3 402 (90558, 21)
T60 3 50 (90816, 21)
T60 3 501 (91074, 21)
T60 3 502 (91332, 21)
T60 3 60 (91590, 21)
T60 3 601 (91848, 21)
T60 3 602 (92106, 21)
T60 3 63 (92364, 21)
T60 3 70 (92622, 21)
T60 3 75 (92880, 21)
T80 0 00 (93138, 21)
T80 0 10 (93396, 21)
T80 0 20 (93654, 21)
T80 0 201 (93912, 21)
T80 0 202 (94170, 21)
T80 0 30 (94428, 21)
T80 0 301 (94686, 21)
T80 0 302 (94944, 21)
T80 0 40 (95202, 21)
T80 0 401 (95460, 21)
T80 0 402 (95718, 21)
T80 0 50 (95976, 21)
T80 0 501 (96234, 21)
T80 0 502 (96492, 21)
T80 0 60 (96750, 21)
T80 0 601 (97008, 21)
T80 0 602 (97266, 21)
T80 0 63 (97524, 21)
T80 0 70 (97782, 21)
T80 0 75 (98040, 21)
T80 2 00 (98298, 21)
T80 2 10 (98556, 21)
T80 2 20 (98814, 21)
T80 2 201 (99072, 21)
T80 2 202 (99330, 21)
T80 2 30 (99588, 21)
T80 2 301 (99846, 21)
T80 2 302 (100104, 21)
T80 2 40 (100362, 21)
T80 2 401 (100620, 21)
T80 2 402 (100878, 21)
T80 2 50 (101136, 21)
T80 2 501 (101394, 21)
T80 2 502 (101652, 21)
T80 2 60 (101910, 21)
T80 2 601 (102168, 21)
T80 2 602 (102426, 21)
T80 2 63 (102684, 21)
T80 2 70 (102942, 21)
T80 2 75 (103200, 21)
T80 3 00 (103458, 21)
T80 3 10 (103716, 21)
T80 3 20 (103974, 21)
T80 3 201 (104232, 21)
T80 3 202 (104490, 21)
T80 3 30 (104748, 21)
T80 3 301 (105006, 21)
T80 3 302 (105264, 21)
T80 3 40 (105522, 21)
T80 3 401 (105780, 21)
T80 3 402 (106038, 21)
T80 3 50 (106296, 21)
T80 3 501 (106554, 21)
T80 3 502 (106812, 21)
T80 3 60 (107070, 21)
T80 3 601 (107328, 21)
T80 3 602 (107586, 21)
T80 3 63 (107844, 21)
T80 3 70 (108102, 21)
T80 3 75 (108360, 21)
T90 0 00 (108618, 21)
T90 0 10 (108876, 21)
T90 0 20 (109134, 21)
T90 0 201 (109392, 21)
T90 0 202 (109650, 21)
T90 0 30 (109908, 21)
T90 0 301 (110166, 21)
T90 0 302 (110424, 21)
T90 0 40 (110682, 21)
T90 0 401 (110940, 21)
T90 0 402 (111198, 21)
T90 0 50 (111456, 21)
T90 0 501 (111714, 21)
T90 0 502 (111972, 21)
T90 0 60 (112230, 21)
T90 0 601 (112488, 21)
T90 0 602 (112746, 21)
T90 0 63 (113004, 21)
T90 0 70 (113262, 21)
T90 0 75 (113520, 21)
T90 2 00 (113778, 21)
T90 2 10 (114036, 21)
T90 2 20 (114294, 21)
T90 2 201 (114552, 21)
T90 2 202 (114810, 21)
T90 2 30 (115068, 21)
T90 2 301 (115326, 21)
T90 2 302 (115584, 21)
T90 2 40 (115842, 21)
T90 2 401 (116100, 21)
T90 2 402 (116358, 21)
T90 2 50 (116616, 21)
T90 2 501 (116874, 21)
T90 2 502 (117132, 21)
T90 2 60 (117390, 21)
T90 2 601 (117648, 21)
T90 2 602 (117906, 21)
T90 2 63 (118164, 21)
T90 2 70 (118422, 21)
T90 2 75 (118680, 21)
T90 3 00 (118938, 21)
T90 3 10 (119196, 21)
T90 3 20 (119454, 21)
T90 3 201 (119712, 21)
T90 3 202 (119970, 21)
T90 3 30 (120228, 21)
T90 3 301 (120486, 21)
T90 3 302 (120744, 21)
T90 3 40 (121002, 21)
T90 3 401 (121260, 21)
T90 3 402 (121518, 21)
T90 3 50 (121776, 21)
T90 3 501 (122034, 21)
T90 3 502 (122292, 21)
T90 3 60 (122550, 21)
T90 3 601 (122808, 21)
T90 3 602 (123066, 21)
T90 3 63 (123324, 21)
T90 3 70 (123582, 21)
T90 3 75 (123840, 21)

- 합쳐진 결과를 csv 파일로 저장한다.(euc-kr 또는 utf-8-sig 추천)

In [23]:
df.to_csv('경제활동인구조사(euc-kr).csv', encoding='euc-kr')
files.download('경제활동인구조사(euc-kr).csv')
df.to_csv('경제활동인구조사(utf-8).csv', encoding='utf-8')
files.download('경제활동인구조사(utf-8).csv')
df.to_csv('경제활동인구조사(utf-8-sig).csv', encoding='utf-8-sig')
files.download('경제활동인구조사(utf-8-sig).csv')